### ISSUE TITLE
Node version in react-scripts-wptheme-utils incompatable with other libraries.

### ISSUE THREAD

**Issue by adigitalnative** [devloco/create-react-wptheme#11]
Might be overkill to do it, but I was trying to set this up with React & Redux and got an error: 

    yarn add redux
    yarn add v1.12.3
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    error @devloco/react-scripts-wptheme-utils@1.3.9: The engine "node" is incompatible with this module. Expected version ">=8". Got "6.11.2"
    error Found incompatible module
    info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Should it be pulling in a more recent version of Node?

**Comment by adigitalnative** [comment]
Update: Also seeing this when attempting to install other packages... react-router, semantic-ui-react...

**Comment by adigitalnative** [comment]
Update: backed out to themes folder, switched to node 8 (`nvm use 8`), then repeated and things now seem to work/be installing. So weird/possibly idiosyncratic issue, but could hit new users who are starting with later versions of Node.

**Comment by devloco** [comment]
Hi, apologies for the delay. 

It looks like you got the issue figured out. Older versions of NPM are not supported by Create-react-app, and thus not supported by this tool either. In fact it looks like Facebook has updated Create-react-app to not allow versions [less than 8.10](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/package.json#L8).

When I finally get around to getting another update out, I'll probably change this tool to match.

**Comment by adigitalnative** [comment]
Appreciate the follow-up! Just as an FYI/clarification in case you circle back to this in an update: The first time I tried, I was using node 11 and I wasn't able to install other packages. It wasn't until I started over with an **older** version of Node that I could install other libraries.

**Comment by devloco** [comment]
Hmm... that is strange. The error message you posted said: `Expected version ">=8". Got "6.11.2"`

Maybe there's a bug in the version detection code. I'll re-open this and take a look at FB's code and see if maybe they made a change that helps.

Thanks for clarifying!

**Comment by devloco** [comment]
And just to add a little clarification myself:

- It was Yarn pulling in the wptheme-utils package, not the wptheme-utils package pulling in anything.
- The wptheme-utils requires that the available version of Node be >= 8 before it will install.
- Since you were using Yarn, and have NVM installed is there any chance that you had your node version set to v6.11.2? Is possible someone else was using this machine and switched the running Node version to that old version?

**Comment by devloco** [comment]
Unfortunately, I'm not able to reproduce this.

![2019-03-28 13_19_53](https://user-images.githubusercontent.com/40293912/55182957-cd04dd80-515c-11e9-9527-df6a8f7c795b.png)
