### ISSUE TITLE
Not a Bug - But a few questions to get started...

### ISSUE THREAD

**Issue by michaelsoriano** [devloco/create-react-wptheme#12]
@devloco  - first - Thank you for this amazing tool. I'm up and running. I'm excited to dive in. 

Although, I have a few questions. 

1) When I create a git repository for my theme - do I do it from the root theme folder (I notice there's a .git folder in react-src)? Do I gitignore node_modules etc?
2) How do I install it in other environments? Do I go through the normal WP installation of the theme? 
3) How does it know which one user.{env}.json file to read, when I move to another server?
4) Just verifying that all server interactions is through WPREST API correct?

Thanks again.

**Comment by devloco** [comment]
- I would only check in the react-src folder to Github. I would `.gitignore` both the `node_modules` and the `build` folders. But really it's up to you. The files in the `build` folder should be the same as the files in the root folder. They get copied from `build` to root each time you save during the dev cycle and as minified files when you run the "npm run build" command.

    - You should notice a "DO NOT MODIFY THESE FILES" file in the root folder during the dev cycle (i.e. when you run "npm run start" command).
    - After running the "npm run build" command that "DO NOT EDIT" file should disappear, and all the folders and files (minus the react-src folder) are your compiled theme. Usually you wouldn't check the compiled versions into Github, but I could see a scenario where you check-in the compiled files into a customer's Github account... as an example.

- Regarding your second question, read this section of the README carefully. Let me know if it doesn't make sense:
    - [Build Configuration](https://github.com/devloco/create-react-wptheme#build-configuration)

- Regarding your 3rd question, it should make sense after understanding the 2nd question, but basically, "npm run start" reads the user.dev.json file and the "npm run build" command reads the user.prod.json file.

- Question 4: Yes, that is the intention. Although there is nothing stopping you from using PHP replacement tags if you need for whatever reason (sometimes jamming a big long JSON string in the head of index.php can be faster than api requests for example... but I would do 100% api requests until I found a problem area).

Thanks for the kind words! I wish you luck!

-joe

**Comment by michaelsoriano** [comment]
Awesome. Yes - they make sense. Let me see how far I get. 

Thanks again - I owe you a beer.

**Comment by devloco** [comment]
Hi @michaelsoriano,

I tried sending an email through your website, but it kept giving me an error (I have a lot of privacy plugins installed... so I usually blame that). Anyway, I hope you see this. Here's the email:


----
Hi Michael,

I noticed that you forked `create-react-wptheme` today. Which reminded me that I've been meaning to post a "How It Works" type of thing to make forking easier.

In reality `create-react-wptheme` doesn't do a whole lot... at all really. All the magic happens in the code in this repo (so you should fork this too):
https://github.com/devloco/create-react-wptheme-scripts

I typed up a little "how it works" post in an issue thread on `create-react-app` a while ago:
https://github.com/facebook/create-react-app/issues/1070#issuecomment-514335715

I've archived some of the repos mentioned there, in that case the mentioned repo has probably just been moved inside the "packages" folder in the `devloco/create-react-wptheme-scripts` repo.

Anyway, I hope that info gets you started a bit quicker on your fork.

Don't hesitate to reach out if you have questions. I can be pretty slow to respond to emails (I just don't check 'em enough)...

Take care,

-joe
devloco@outlook.com

**Comment by michaelsoriano** [comment]
Hi Joe,

That form was always buggy. I have to replace that soon.

Also, yes - Good to know about the other repo + instructions.  

We've already launched a site that's using your code. And we're thinking of building additional ones - because the first one worked out so well. 

The development experience is so much better - I can't thank you enough. 

I will email you my contact info - just in case you need it. 

Again thank you so much.

Michael
