### ISSUE TITLE
Component are not reflecting 

### ISSUE THREAD

**Issue by rajadileepkumar** [devloco/create-react-wptheme#13]
My App is working is fine.styles are reflecting and components are not reflecting content and new components with routing not working

**Comment by devloco** [comment]
This is a good tutorial that includes routing:

[How to Build a Skin With React and WordPress](https://www.smashingmagazine.com/2018/03/react-wordpress-web-app/)

If you use `create-react-wptheme`, then you can skip all the setup steps from that tutorial. Search for the phrase:

> Extending The WordPress REST API

For a good starting place after getting your theme setup using `create-react-wptheme`.

The author of that tutorial has been keeping his Github repo up to date, here:

[Celestial React-WordPress Theme](https://github.com/m-muhsin/celestial)

Good luck!

**Comment by rajadileepkumar** [comment]
Hi @devloco ,

Thanks for the response.my issue resolved
