### ISSUE TITLE
Error when running npx create-react-wptheme themename

### ISSUE THREAD

**Issue by michaelsoriano** [devloco/create-react-wptheme#18]
I'm running into a new error on a fresh installation. When I run 

**npx create-react-wptheme themename**

It doesn't seem to complete the install. I get: 

```
+ @devloco/react-scripts-wptheme@3.0.1-wptheme-3.0.0
added 1423 packages from 732 contributors and audited 892165 packages in 141.248s
found 0 vulnerabilities

internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'C:\wamp\www\wordpress\wp-content\themes\newtheme\react-src\node_modules\package.json'
```

I try to run wpstart anyway - by going into react-src and doing a npm run wpstart, and I get 

```
$ npm run wpstart
npm ERR! missing script: wpstart
```

The package.json contains very little stuff:

```
{
  "name": "react-src",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@devloco/react-scripts-wptheme": "3.0.1-wptheme-3.0.0"
  }
}
```

Any ideas?

**Comment by devloco** [comment]
I'll take a look today. I'm hoping some other package broke and it'll just fix itself... I swear I tested it before publishing the latest update! :-(

**Comment by devloco** [comment]
I just tried and it worked. My installation showed:

`added 1426 packages from 732 contributors`

So I got 3 more packages than you did... so hopefully my earlier guess was right, and some other package got fixed.

Give it a try and let me know.

Thanks! I really do appreciate the feedback.

**Comment by michaelsoriano** [comment]
We're back in business! Thanks for the quick response.

**Comment by michaelsoriano** [comment]
@devloco  - btw, I have my tutorial up http://michaelsoriano.com/wordpress-theme-react-part-1-setup/

**Comment by devloco** [comment]
That's awesome! I'll update the README tonight.

**Comment by devloco** [comment]
Readme updated both here and on NPM.
Thanks again for doing that!
