### ISSUE TITLE
 Fixed

### ISSUE THREAD

**Issue by nathankjos** [devloco/create-react-wptheme#19]

**Comment by devloco** [comment]
Hmm... you say everything is working? Just to double-check everything, here are some screenshots of what everything working in Firefox looks like:

![2019-05-29 10_59_19](https://user-images.githubusercontent.com/40293912/58572667-baad2b80-8201-11e9-900b-c86977e09459.png)

![2019-05-29 10_59_23](https://user-images.githubusercontent.com/40293912/58572671-bf71df80-8201-11e9-9627-26b475b23832.png)

![2019-05-29 11_03_59](https://user-images.githubusercontent.com/40293912/58572676-c4369380-8201-11e9-967c-6c980c75df04.png)

If any of that differs (other than Safari vs Firefox differences), the things I can think of that might be causing it are:

1. Is this an existing theme? Maybe updating to the latest version will help: [Updating Existing Themes](https://github.com/devloco/create-react-wptheme#updating-existing-themes)
2. I've run into strange errors when I mix and match `yarn` and `npm` ... if the `create-react-wptheme` command used one (say `yarn`) and you later used `npm` for some operation, it can cause strange errors. Just nuke the `node_modules` folder and `yarn` or `npm install` to recreate the `node_modules` folder.
3. Last, but not least, I see you're running `https` ... you should configure the little websocket server to run over `SSL` as well. I know Firefox shows weird errors when running the site over `https` but not the websocket server, instructions here: [HTTPS/SSL Support](https://github.com/devloco/create-react-wptheme#httpsssl-support)

Hopefully one of those ideas works for you. Please, let me know. I don't have access to Safari... 

Thanks!

**Comment by devloco** [comment]
lol you closed this while I was typing. Did you get it figured out?
