### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by jlucfarias** [devloco/create-react-wptheme#21]
Hi, i created a theme with `npx create-react-wptheme testetheme` but i can't even build. I'm using the latest version

The response when i run `yarn build` is `TypeError: Cannot read property 'homepage' of null at module.exports (C:\Users\lucas\Documents\testetheme\node_modules\@devloco\react-scripts-wptheme\config\webpack.config.wptheme.js:77:25)`

[testetheme.zip](https://github.com/devloco/create-react-wptheme/files/3316789/testetheme.zip)

**Comment by devloco** [comment]
Hi @John-Luke , I'm creating a new theme as I type this to check this out.

But the first thing that comes to mind is: did you complete the PHP portion of the setup?

**Comment by devloco** [comment]
Hi @John-Luke,

Yes I get this exact same error if I run `yarn build` without completing the PHP portion of the setup. Thanks for pointing this out.

I'll improve the script to at least print a nicer error.... or maybe I'll run `yarn start` for you when all configs are missing.

**Comment by devloco** [comment]
I actually already had code to do this check, but it wasn't executing soon enough in the process.

Fixed now in `@devloco/react-scripts-wptheme` version `3.0.1-wptheme-3.0.5`.
