### ISSUE TITLE
Build succces... ERROR: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by ghost** [devloco/create-react-wptheme#22]
I have an issue with building my theme. 
Everything works, it builds the theme successfully and I'm able to select the theme within the WP back-end. But when I'm going to view my theme, I see a blank page with multiple errors in the console that say "failed to load resource". At this point I don't know what I'm doing wrong, I followed your tutorial "Let's build a WordPress theme with React: Part 1 (Setup)" but I couldn't find the anwser there.

The steps I take:
- (within react-src) npm run wpbuild -- I get the succes message: The build folder is ready to be deployed.
- (wp back-end) change and activate the the build version of the theme. (The dev version says "ERROR: Stylesheet is missing." and is removed when activating the build version)
- View site, I press on Visit site "New theme activated. Visit site"

The errors I get in the console:
- Failed to load resource: the server responded with a status of 404 (Not Found): main.2cce8147.chunk.css:1
- Failed to load resource: the server responded with a status of 404 (Not Found): 22.b41502e9.chunk.js:1
- Failed to load resource: the server responded with a status of 404 (Not Found): main.f058206c.chunk.js:1 
- Failed to load resource: the server responded with a status of 404 (Not Found): main.2cce8147.chunk.css:1

**Comment by devloco** [comment]
Hi @N0GKW, 

It looks like you missed doing the `npm run start` command...?

`npm run build` is for building your final production files to be deployed to your production server.

`npm run start` is what you use while developing your theme.

Give that a try and let me know. Good luck!

**Comment by ghost** [comment]
Thank you for your respons, but that's not what I mean. I want to deploy my theme so It wil run on a production server. Developing works perfectly with npm run start and I'm able to develop my theme. The issue I have is that now it's finished, when I build the production version. I get a blank screen with errors, but the development versions works.

**Comment by devloco** [comment]
Ah, yes. That tends to bite quite a few people.
Here are the instructions that should get you going: [dealing-with-differing-paths-between-dev-and-prod](https://github.com/devloco/create-react-wptheme#dealing-with-differing-paths-between-dev-and-prod).

**Comment by ghost** [comment]
Ok, but on my localhost the paths don't change right? or am I missing something here?

**Comment by devloco** [comment]
Sounds like you got it.

When you run `npm run start` it will rebuild the theme using the homepage path from the package.json file.

And when you run `npm run build` it will rebuild the theme using the homepage path from `user.prod.json`.

A theme built using `npm run start` will be broken on a PROD server.
A theme built using `npm run build` will be broken on a DEV server.

**Comment by ghost** [comment]
Ok perfect thanks!
