### ISSUE TITLE
Cannot find module './yarn.lock.cached'

### ISSUE THREAD

**Issue by benjaminluoma** [devloco/create-react-wptheme#3]
Trying to install via npx create-react-wptheme my_theme but... get getting this:

Cannot find module './yarn.lock.cached'

**Comment by devloco** [comment]
Hi Benjamin, apologies for the delay.
I just published a new version of create-react-wptheme to NPM. Version 2.0.5.

When you run "npx create-react-wptheme my_theme" you should see it say:

2.1.1-wptheme-2.0.5

The 2.1.1 is the current version of Facebook's create-react-app, which wptheme uses to scaffold the theme.

If you continue to see that error, it might be that you have create-react-app installed globally on your machine...? And if so, maybe it's an older version?

I wasn't able to actually reproduce your error, so I just removed all the Yarn stuff from create-react-wptheme, as it isn't necessary. So the only thing that is using Yarn now would be create-react-app proper.

**Comment by devloco** [comment]
This should be fixed. I've basically eradicated yarn from the entire process. NPM only from here on out.
