### ISSUE TITLE
Deploying theme to server has blank page 

### ISSUE THREAD

**Issue by ShrkBnk** [devloco/create-react-wptheme#32]
In development server (localhost) everything works fine. 
But after npm run build get folder that I deploy to wordrpess server. 
It appears in theme section I can choose it, but it appears only blank page with some errors:

**Comment by devloco** [comment]
I saw you closed this, but just wanted to be sure you got it working. I'm guessing you had different root paths in Dev and Prod...? And you found the instructions...?

[Dealing With Differing Paths Between DEV and PROD](https://github.com/devloco/create-react-wptheme#dealing-with-differing-paths-between-dev-and-prod)

**Comment by ShrkBnk** [comment]
Yes , I got it working, I had different root path in Dev and Prod. 
Thanks.
