### ISSUE TITLE
help me ! !

### ISSUE THREAD

**Issue by kenket000** [devloco/create-react-wptheme#42]
i can't run 
npx create-react-wptheme
when i run then error....
create-react-wptheme version: 3.3.1-wp.3
@devloco/react-scripts-wptheme version: ^3.3.1-wp.2

Creating a new React WP theme in C:\xampp\htdocs\ReactJS\wp-content\themes\reactjs.
Using Create React App 3.3.1 to scaffold the theme's source code...

Error: EEXIST: file already exists, mkdir 'C:\Users\Vo'
TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:97:27)
    at errorHandler (C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:216:3)
    at C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:78:20
    at cb (C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\lib\npm.js:225:22)
    at C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\lib\npm.js:263:24
    at C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:171:20)
C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:97:27)
    at process.errorHandler (C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:216:3)
    at process.emit (events.js:321:20)
    at process._fatalException (internal/process/execution.js:165:25)
Install for [ 'create-react-app@3.3.1' ] failed with code 7
(node:6200) UnhandledPromiseRejectionWarning: ReferenceError: reject is not defined
    at C:\Users\Vo Dong Ho\AppData\Roaming\npm\node_modules\create-react-wptheme\createReactWpTheme.js:278:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). 
(rejection id: 1)
(node:6200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.  

help me !!!!!

**Comment by devloco** [comment]
Hi @kenket000,

I was not able to reproduce this. Everything worked for me just now.

The error messages you are getting are **very strange.**

`Error: EEXIST: file already exists, mkdir 'C:\Users\Vo'`
and
`Install for [ 'create-react-app@3.3.1' ] failed with code 7`

It sounds like something is wrong with your user account on your computer. Almost like you don't have permission to modify your own user folder...?

**Comment by devloco** [comment]
FYI: I will put in the `catch` statement that your errors want. I'll do that now, and then publish a new release. That might give you more information if the error happens again.

Give me 30 minutes to do that. I'll post back in here when it's ready.

**Comment by kenket000** [comment]
Tks u ! I'll try again !

Vào 13:35, T.3, 11 Th2, 2020 devloco <notifications@github.com> đã viết:

**Comment by devloco** [comment]
The new version is published to NPM now, it should say this when it starts (note: `3.3.1-wp.4`):

@devloco/create-react-wptheme version: **3.3.1-wp.4**
@devloco/react-scripts-wptheme version: ^3.3.1-wp.2

Creating a new React WP theme in E:\WPDev\xampp\htdocs\wordpress\wp-content\themes\test02.
Using Create React App 3.3.1 to scaffold the theme's source code...

**Comment by kenket000** [comment]
tks U ! i installed success ! Thank you for supporting me! I found the cause because my user directory named has spaces! I fixed the error and run normally! Thank you very much!!!

**Comment by devloco** [comment]
Great! And thanks for reporting the issue.

**Comment by devloco** [comment]
Note to self: I changed the issue tags to "bug" since my code was not properly handling the exceptions.
