### ISSUE TITLE
User Guide internal links not working

### ISSUE THREAD

**Issue by emirhg** [devloco/create-react-wptheme#52]
The user guide seems to be missing some parts, as no link from the Table of Contents is working

Example: https://github.com/devloco/create-react-wptheme/blob/master/create-react-app-USERGUIDE.md#code-splitting

**Comment by devloco** [comment]
That file is very old and needs to be deleted. Thanks for reminding me:-)

You are looking for this:
https://create-react-app.dev/docs/getting-started/

Be sure to know the minor differences between that project and this one. You can find the differences in this project’s README, in particular the section here:

https://github.com/devloco/create-react-wptheme/blob/master/README.md#react-tutorials

Apologies for the confusion!

**Comment by devloco** [comment]
Also, be sure to check out the tutorial linked from the “Getting Started” section at the top of this project’s README.

**Comment by devloco** [comment]
Old CRA user guide is now deleted from the master branch.
