### ISSUE TITLE
Non-Local Wordpress getting 404 on bundle.js for generated theme

### ISSUE THREAD

**Issue by semaurer** [devloco/create-react-wptheme#8]
This is more of a question than an issue, not sure how else to contact you.

This is working perfectly on my local Wordpress.  When I transfer the theme to my actual wordpress account and activate the theme, the index file gets a 404 on "theme"/static/js/bundle.js.  When I SSH into my box, I can see that the bundle.js file is there even though it's getting a 404.

Do the WPBuild and WPstart commands have to be run on the particular box it's running on?  Or could you export the entire theme and expect it to work out of the box?

Thanks.

**Comment by devloco** [comment]
No worries, just based on a guess here, but I'm guessing your root path on your dev machine is different than on the prod machine.

Check out this section of the README on how to set root before running `wpbuild`:

[Build Configuration](https://github.com/devloco/create-react-wptheme#build-configuration)

**Comment by semaurer** [comment]
That's definitely it.  Thanks a bunch.
