### ISSUE TITLE
user.prod.json homepage property not used on wpbuild

### ISSUE THREAD

**Issue by mikelinden1** [devloco/create-react-wptheme#9]
When I run `node run wpbuild` the `homepage` property set in `user.prod.json` isn't used - it uses the `homepage` property in my `package.json`. I also tried removing the homepage prop in package.json and moving it to user.dev.json but then it used the root as the homepage.

**Comment by mikelinden1** [comment]
Also, thank you for creating this amazing tool - it solved some headaches!

**Comment by devloco** [comment]
That's a bummer. I'll take a look this weekend and get 'er fixed.

**Comment by devloco** [comment]
And thanks for the kind words!

**Comment by devloco** [comment]
I haven't had a chance to look at this yet, but I was thinking, maybe you're running an older version? There was a time that the build command was a known problem:
#5 
And then recently someone else seemed to indicate that changes to user.prod.json worked for them:
#8 

So I'm wondering if maybe you started the theme you're working from the known-bad-build version, and maybe updating to the latest will get it sorted out. Updating instructions here:
[Updating](https://github.com/devloco/create-react-wptheme#updating)

Anyway, I'm still planning to look at this tomorrow or Sunday, but if you're running the old version, then you can get yourself working tonight.

**Comment by mikelinden1** [comment]
I just ran the update and it took me to `"@devloco/react-scripts-wptheme": "^2.1.2-wptheme-2.1.5",` (I was on `"@devloco/react-scripts-wptheme": "2.1.1-wptheme-2.1.4",` before) but the problem persists. Thanks for your help so far!

**Comment by devloco** [comment]
FYI: I am able to reproduce this. I'll get a fix out tonight.

**Comment by devloco** [comment]
I was able to get `npm run build` to work with `@devloco/react-scripts-wptheme` version `2.1.2-wptheme-2.1.9`.

Hopefully that'll work for you as well. I'll leave this ticket open for now.

Apologies for the delay!

**Comment by mikelinden1** [comment]
Oh great. I'll take a look tomorrow and let you know!

**Comment by mikelinden1** [comment]
That did the trick - thank you!!
